### ISSUE TITLE
Autocomplete name on checkout base on TablePress list of users

### ISSUE THREAD

**Issue by levansy2020** [haiyen09clc/ifdresourc.es#1]

**Comment by bentupper** [comment]
Can you explain what lines of code do this, and if I need to edit the TablePress table being referenced, which specific line I would need to edit to do that? Thank you!

**Comment by haiyen09clc** [comment]
> Can you explain what lines of code do this, and if I need to edit the TablePress table being referenced, which specific line I would need to edit to do that? Thank you!

Hi Ben, I made a mistake while commiting the code for this issue so i deleted it from the current plugin.php. Sy will upload the code for this issue and explain to you later.

**Comment by bentupper** [comment]
Sounds good. Thank you. Nice to talk to you again :)
